---
title: "COVID-19"
author: "Ethan Tenison"
date: "3/22/2020"
output: html_document
---

```{r libraries_data, message=FALSE}

library(tidyverse)
library(RCurl)
library(janitor)
library(sjmisc)
library(reshape2)
library(lubridate)
library(sf)
library(raster)
library(dplyr)
library(DataCombine)

X03_10_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-10-2020.csv")
X03_11_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")
X03_12_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-12-2020.csv")
X03_13_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")
X03_14_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-14-2020.csv")
X03_15_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-15-2020.csv")
X03_16_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-16-2020.csv")
X03_17_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv")
X03_18_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-18-2020.csv")
X03_19_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-19-2020.csv")
X03_20_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-20-2020.csv")
X03_21_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-21-2020.csv")
X03_22_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv")
X03_23_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv")
X03_24_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-24-2020.csv")
X03_25_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-25-2020.csv")
X03_26_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-26-2020.csv")
X03_27_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv")
X03_28_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-28-2020.csv")
X03_29_2020 <- read_csv("csse_covid_19_data/csse_covid_19_daily_reports/03-29-2020.csv")
```


```{r add_date}

X03_10_2020 <- X03_10_2020 %>% mutate(date = "03_10_2020") %>% dplyr::select(-c("Last Update")) %>% clean_names() %>% rename(lat = latitude, long = longitude) %>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0) %>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_11_2020 <- X03_11_2020 %>% mutate(date = "03_11_2020") %>% dplyr::select(-c("Last Update"))%>% clean_names() %>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_12_2020 <- X03_12_2020 %>% mutate(date = "03_12_2020") %>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_13_2020 <- X03_13_2020 %>% mutate(date = "03_13_2020") %>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_14_2020 <- X03_14_2020 %>% mutate(date = "03_14_2020") %>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_15_2020 <- X03_15_2020 %>% mutate(date = "03_15_2020") %>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_16_2020 <- X03_16_2020 %>% mutate(date = "03_16_2020")%>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_17_2020 <- X03_17_2020 %>% mutate(date = "03_17_2020")%>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_18_2020 <- X03_18_2020 %>% mutate(date = "03_18_2020")%>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_19_2020 <- X03_19_2020 %>% mutate(date = "03_19_2020")%>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_20_2020 <- X03_20_2020 %>% mutate(date = "03_20_2020")%>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_21_2020 <- X03_21_2020 %>% mutate(date = "03_21_2020")%>% dplyr::select(-c("Last Update"))%>% clean_names()%>% rename(lat = latitude, long = longitude)%>% mutate(fips = "NA", admin2 = "NA", combined_key = "NA", active = 0)%>% dplyr::select(fips, admin2, province_state ,country_region ,lat , long ,confirmed,deaths,recovered, active,combined_key ,date)
X03_22_2020 <- X03_22_2020 %>% mutate(date = "03_22_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_23_2020 <- X03_23_2020 %>% mutate(date = "03_23_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_24_2020 <- X03_24_2020 %>% mutate(date = "03_24_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_25_2020 <- X03_25_2020 %>% mutate(date = "03_25_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_26_2020 <- X03_26_2020 %>% mutate(date = "03_26_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_27_2020 <- X03_27_2020 %>% mutate(date = "03_27_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_28_2020 <- X03_28_2020 %>% mutate(date = "03_28_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()
X03_29_2020 <- X03_29_2020 %>% mutate(date = "03_29_2020")%>% dplyr::select(-c("Last_Update"))%>% clean_names()



```




```{r all data merge}

dfold <- bind_rows(X03_10_2020,X03_11_2020,X03_12_2020,X03_13_2020,X03_14_2020,X03_15_2020,X03_16_2020,X03_17_2020,X03_18_2020,X03_19_2020,X03_20_2020,X03_21_2020)



X03_22_2020$fips <- as.character(X03_22_2020$fips)

df <- bind_rows(dfold, X03_22_2020, X03_23_2020, X03_24_2020, X03_25_2020, X03_26_2020,X03_27_2020,X03_28_2020, X03_29_2020   )
df$date <- mdy(df$date)
#df <- df %>% arrange(date, date, desc(confirmed))


```




```{r save_global}
write.csv(df, "covid_global.csv")


```


```{r states, warning = FALSE, message= FALSE}
states <- df %>% filter(country_region == "US") %>% filter(province_state != "Diamond Princess") %>% filter( province_state != "Grand Princess") %>% filter( province_state != "Wuhan Evacuee")%>% filter( province_state != "Recovered") %>% filter( province_state != "recovered")%>% filter( province_state != "US" )



fix_coord <- filter(X03_19_2020, !is.na(province_state))

for (i in 1:length(states$province_state)){
  
  for (j in 1:length(fix_coord$province_state)){
    
    if(states$province_state[i] == fix_coord$province_state[j]){
      states$lat[i] <- fix_coord$lat[j]
      states$long[i] <- fix_coord$long[j]
    }
  }
}

states <- dplyr::select(states, -c(combined_key, fips, admin2, country_region))
states <- states %>% group_by(date, province_state,lat, long) %>% summarize(confirmed = sum(confirmed),recovered = sum(recovered), deaths = sum(deaths))
states <- mutate(states, death_rate= deaths/confirmed)


```



```{r states_long, warning = FALSE, message= FALSE}
states<- states %>% arrange(province_state, date)
states <- PercChange(states, Var = "confirmed", GroupVar = c("date", "province_state"), NewVar = "c_PercentChange", slideBy = -1, type = "percent"  )
states <- PercChange(states, Var = "deaths", GroupVar = c("date", "province_state"), NewVar = "d_PercentChange", slideBy = -1, type = "percent"  )
states <- states %>% mutate_at("death_rate", round, digits = 3) %>% rename(Deaths = deaths, Recovered = recovered, State = province_state)
states <- states %>% mutate_at("c_PercentChange", round, digits = 3) %>% mutate_at("d_PercentChange", round, digits = 3)
states <- gather(states, measure, value, confirmed:Deaths, factor_key=TRUE)
states<- states %>% arrange(date, desc(value))
states$measure <- as.character(states$measure)

for (i in 1:length(states$measure)){
  
  if(states$measure[i] == "confirmed"){
    states$measure[i] <- "Confirmed Cases"
  }
 
  
}



```

```{r states_save}

write.csv(states, "states.csv")
```
